@startuml Laewtae System Use Case Diagram
left to right direction
actor "User" as user
rectangle "LaewtaeDentalClinicSystem" as LaewtaeDentalClinic {    
    usecase "Register" as register
    usecase "View\nDentists" as viewDentists
    usecase "Manage\nBooking" as manageAppt
    usecase "Manage\nDentist" as manageDentist
}

user -- register
user -- viewDentists
user -- manageAppt

actor "Admin" as admin
register -- admin
manageDentist -- admin
manageAppt -- admin
@enduml