@startuml Manage Booking (PUT)

header Laewtae Dental Clinic Sequence Diagram
footer Page %page% of %lastpage%
title "Manage Booking (PUT)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<middleware>>\n:mail" as mail
participant "<<router>>\n:bookings" as routerBookings
participant "<<middleware>>\n:auth" as auth
participant "<<service>>\n:jwt" as jwt
participant "<<controllers>>\n:bookings" as controllersBookings
participant "<<model>>\n:Booking" as modelBooking
database "<<MongoDB>>\n:users" as UsersDatabase
database "<<MongoDB>>\n:bookings" as BookingsDatabase

client->server ++:req.put('/bookings/:id')
server->routerBookings ++:app.use('/bookings/:id', bookings)
routerBookings -> auth ++:protect()
auth -> jwt ++:verify(token, secret)
auth <- jwt --:decoded
auth -> modelBooking ++:findById(decoded, id)
modelBooking -> UsersDatabase ++:UserSchema
modelBooking <- UsersDatabase --:user
auth <- modelBooking --:req.user
routerBookings <- auth --:next()

routerBookings -> auth ++:authorize("admin",""user)
routerBookings <-- auth --:next()

routerBookings -> auth ++:updateBooking()
auth -> controllersBookings ++:updateBooking()
controllersBookings->modelBooking ++:findById(req.params.id)
modelBooking ->BookingsDatabase ++: BookingSchema
BookingsDatabase --> modelBooking --: booking
controllersBookings <-- modelBooking --:booking
routerBookings <-- controllersBookings --:booking
mail <-- routerBookings ++:sendConfirmationEmail
client <- mail --:sendConfirmationEmail
controllersBookings->client --:response

@enduml